export const data: Project[] = [
    {
        title: "ClosingTime",
        img: "closingTime",
        description:
            "Tells you when restaurants are offering closing time discounts.",
        languages: "React",
        siteURL: "https://closeti.me",
        dateCreated: "14/04/2018",
    },
    {
        title: "SprogGo",
        img: "sprogGo",
        description: "Learn a new language easily and actively.",
        languages: "Android",
        githubURL: "https://github.com/alexander7161/SprogGo",
        downloadURL:
            "https://github.com/alexander7161/SprogGo/releases/download/1.1.0/SprogGo-1.1.0.apk",
        dateCreated: "17/02/2018",
    },
    {
        title: "MIHC",
        img: "MIHC",
        description: "An electronic Healthcare System.",
        languages: "Android",
        githubURL: "https://github.com/alexander7161/MyIndividualHealthCare",
        downloadURL:
            "https://github.com/alexander7161/MyIndividualHealthCare/releases/download/1.0.0/MIHC.apk",
        dateCreated: "17/03/2018",
    },
    {
        title: "Alexanderdavis.net",
        img: "alexanderdavisnet",
        description: "My personal website.",
        languages: "React",
        githubURL: "https://github.com/alexander7161/Alexanderdavis.net-React",
        dateCreated: "02/04/2018",
    },
    {
        title: "Shappy",
        img: "shappy",
        description:
            "Allows you to search items on leboncoin using your camera. Personalises results.",
        languages: "Android",
        githubURL: "https://github.com/alexander7161/Shappy",
        downloadURL: "https://github.com/alexander7161/Shappy/releases/",
        dateCreated: "26/05/2018",
    },
    {
        title: "SnapCV",
        img: "snapCV",
        description: "Video CVs for the 21st century.",
        languages: "React",
        githubURL: "https://github.com/octavius464/SnapCV",
        dateCreated: "19/10/2018",
        siteURL: "https://snap-cv.herokuapp.com/",
    },
    {
        title: "CityScanner",
        img: "cityScanner",
        description: "Tinder for CityScanner. Find your perfect destination.",
        languages: "React",
        githubURL: "https://github.com/alexander7161/CityScanner",
        dateCreated: "03/11/2018",
        siteURL: "https://city-scanner.herokuapp.com/",
    },
    {
        title: "Pledgr",
        img: "pledgr",
        description: "Create decentralised pledges.",
        languages: "Solidity",
        githubURL: "https://github.com/alexander7161/pledgr",
        dateCreated: "26/01/2019",
    },
    {
        title: "Video Game Soc",
        img: "videoGameSoc",
        description: "Video game society game rental platform. Built with Laravel.",
        languages: "PHP",
        githubURL: "https://github.com/alexander7161/lab-video-game",
        siteURL: "https://video-game-soc.herokuapp.com/",
        dateCreated: "01/12/2018",
    },
    {
        title: "Alzheimer's Assistant",
        img: "AlzheimerAssistant",
        description: "A Cisco Spark chat bot for patients with alzheimer's.",
        languages: "Python",
        githubURL: "https://github.com/Futuramistic/Bot",
        dateCreated: "17/02/2018",
    },
];
