name: CI
on: push
jobs:
  test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js
        uses: actions/setup-node@master
        with:
          node-version: "10.x"
      - uses: c-hive/gha-npm-cache@v1
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Tests
        run: npm run test
      - name: TSC
        run: npm run tsc
  build:
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js
        uses: actions/setup-node@master
        with:
          node-version: "10.x"
      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}-next
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - uses: actions/upload-artifact@master
        if: github.ref == 'refs/heads/master'
        with:
          name: build
          path: .next
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: [test, build]
    steps:
      - uses: actions/checkout@master
      - uses: actions/download-artifact@master
        with:
          name: build
          path: .next
      - uses: c-hive/gha-npm-cache@v1
      - name: Install dependencies
        run: npm ci
      - name: export
        run: npm run export
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.HOST }}/${{ secrets.HOST_PATH }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.PASSWORD }}
          local-dir: src/out/
