name: build and deploy
on:
  push:
    branches:
      - master
      - develop
jobs:
  test:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js
        uses: actions/setup-node@master
        with:
          node-version: "12.x"
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: build deploy
        run: |
          npm install --prefix ./deploy/
          npm run tsc --prefix ./deploy/
      - name: build deploy
        if: github.ref == 'refs/heads/master'
        run: node ./deploy/build/deploy.js
